on:
  push:
    branches:
      - main  # Replace with your branch name if different

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 1: Run Tests
    - name: Run Unit Tests
      run: |
        npm install
        npm test  # Run your project's test script (adjust for your stack)

    # Step 2: Lint Code
    - name: Lint Code
      run: |
        npm install
        npm run lint  # Example for linting (adjust for your project)

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@3.1.1  # Use this supported version
      with:
        ftp-server: ${{ secrets.FTP_HOST }}  # Correct key
        ftp-username: ${{ secrets.FTP_USERNAME }}  # Correct key
        ftp-password: ${{ secrets.FTP_PASSWORD }}  # Correct key
        local-dir: ./  # Your local directory
        server-dir: /public_html/  # Your Hostinger web directory
